name: aws_iot_client
description: "A Flutter project for test aws iot core"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.8
  mqtt_client: ^10.5.1 
  flutter_bloc: ^8.1.6
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/certs/


